CHAT_USERNAME = "drone"
CHAT_PASSWORD = "12345678"
CHAT_ADDRESS = "localhost:5000"

CHAT_AUTHENTICATION_URL = f"http://{CHAT_ADDRESS}/token"
CHAT_SOCKET_URL = f"ws://{CHAT_ADDRESS}/socket/{CHAT_USERNAME}"

DRONE_IP = "172.19.16.1"
DRONE_PORT = 14550


